[package]
name = "rustcom"
authors = ["Aleksa Jonić <ullnorse@gmail.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"