[package]
name = "rustcom"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.31.1"
eframe = "0.31.1"
egui_dock = "0.16.0"
crossbeam = "0.8.4"
serialport5 = "5.0.2"
anyhow = "1"
thiserror = "2"
clipboard = "0.5.0"
log = "0.4.26"
clap = {version = "4.5.32", features = ["derive"]}
serialport = "4.7.0"
rfd = "0.15.3"
directories = "6.0.0"
open = "5.3.2"

# [lints.rust]
# unused_qualifications = "warn"

# [lints.clippy]
# pedantic = { level = "warn", priority = -1 }