[workspace]
members = [
    "base",
    "gui",
    "tui",
    "rustcom"
]

resolver = "2"

[workspace.dependencies]
base = { path = "base" }
gui = { path = "gui" }
tui = { path = "tui" }
rustcom = { path = "rustcom" }

anyhow = "1.0"
log = "0.4"
env_logger = "0.11"