[package]
name = "rustcom"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.29.1"
eframe = "0.29.1"
egui_dock = "0.14.0"
crossbeam = "0.8.4"
serialport5 = "5.0.2"
anyhow = "1"
thiserror = "1.0"
clipboard = "0.5.0"
log = "0.4.22"
clap = {version = "4.5.20", features = ["derive"]}