[package]
name = "rc-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = {version = "4.1.8", features = ["derive"]}
serial2 = "0.1.7"
serialport = "4.2.0"
flume = "0.10.14"